services:
  postgres:
    image: postgres
    container_name: notes_api_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notes_api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: