spring:
  application:
    name: notes_api
  app:
    jwt: PZTpk3by4ybNqGO/A6BU1dysEcP2e7To9dKmAbgsEsa2jqLBqvnCsqdAMjHGft6K5JtN4zeoSW4JFswMqpjaVclDSC4W49NaH11seniKz6M=
    jwtExpirationMs: 172800000

  datasource:
    url: jdbc:postgresql://localhost:5432/notes_api
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

    com:
      yanvelasco:
        notes_api: DEBUG